version: "3.2"

services:
  app:
    image: monooso/docker-php:7.1
    depends_on:
      - mysql
      - redis
    volumes:
      - ${PATH_APP_ROOT}:/var/code

  email:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 1080:8025

  mysql:
    image: monooso/docker-mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    user: "1000"
    volumes:
      - ${PATH_DATA_ROOT}/mysql:/var/lib/mysql:delegated

  nginx:
    image: monooso/docker-nginx:1.13
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${PATH_APP_ROOT}:/var/code/app:ro
      - ${PATH_CONFIG_ROOT}/nginx/sites:/etc/nginx/conf.d:ro

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
